name: receitas_trabalho_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_expandable_fab: ^2.5.0
  http: ^1.4.0
  logger: ^2.5.0
  path: ^1.9.1
  provider: ^6.1.5
  sqflite: ^2.4.2
  uuid: ^4.5.1
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
